/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T10:47:12.012030

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'tool_call.zorphy.dart';
part 'tool_call.g.dart';

/// ToolCall entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $ToolCall {

  String get toolName;
  Map<String, dynamic> get arguments;
  ToolCallStatus get status;
  String? get result;
  String? get error;
  DateTime? get executedAt;
}

