/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:03:23.059084

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../tool_scope/tool_scope.dart';

part 'tool_configuration.zorphy.dart';
part 'tool_configuration.g.dart';

/// ToolConfiguration entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $ToolConfiguration {
  String get id;
  String get workspaceId;
  String get toolName;
  bool get isEnabled;
  $ToolScope? get scope;
  List<ToolPermission> get permissions;
  Map<String, dynamic>? get configOverrides;
  DateTime? get lastUsedAt;
  int get usageCount;
}
