// Generated by zfa
// zfa generate Conversation --methods=get,getList,create,delete --repository

import 'package:zuraffa/zuraffa.dart';
import '../entities/conversation/conversation.dart';

abstract class ConversationRepository {
  Future<Conversation> get(QueryParams<Conversation> params);
  Future<List<Conversation>> getList(ListQueryParams<Conversation> params);
  Future<Conversation> create(Conversation conversation);
  Future<void> delete(DeleteParams<String> params);
}
