// Generated by zfa
// zfa generate Message --methods=get,getList,create,update,delete,watch,watchList --repository

import 'package:zuraffa/zuraffa.dart';
import '../entities/message/message.dart';

abstract class MessageRepository {
  Future<Message> get(QueryParams<Message> params);
  Future<List<Message>> getList(ListQueryParams<Message> params);
  Future<Message> create(Message message);
  Future<Message> update(UpdateParams<String, Partial<Message>> params);
  Future<void> delete(DeleteParams<String> params);
  Stream<Message> watch(QueryParams<Message> params);
  Stream<List<Message>> watchList(ListQueryParams<Message> params);
}
