// Generated by zfa
// zfa generate ToolConfiguration --methods=get,getList,update --repository

import 'package:zuraffa/zuraffa.dart';
import '../entities/tool_configuration/tool_configuration.dart';

abstract class ToolConfigurationRepository {
  Future<ToolConfiguration> get(QueryParams<ToolConfiguration> params);
  Future<List<ToolConfiguration>> getList(
    ListQueryParams<ToolConfiguration> params,
  );
  Future<ToolConfiguration> update(
    UpdateParams<String, Partial<ToolConfiguration>> params,
  );
}
