// Generated by zfa
// zfa generate Workspace --methods=get,getList,create,update,delete --repository

import 'package:zuraffa/zuraffa.dart';
import '../entities/workspace/workspace.dart';

abstract class WorkspaceRepository {
  Future<Workspace> get(QueryParams<Workspace> params);
  Future<List<Workspace>> getList(ListQueryParams<Workspace> params);
  Future<Workspace> create(Workspace workspace);
  Future<Workspace> update(UpdateParams<String, Partial<Workspace>> params);
  Future<void> delete(DeleteParams<String> params);
}
