/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T10:47:16.555327

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../tool_call/tool_call.dart';

part 'message_metadata.zorphy.dart';
part 'message_metadata.g.dart';

/// MessageMetadata entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $MessageMetadata {
  int? get tokenCount;
  String? get model;
  String? get provider;
  int? get latencyMs;
  List<$ToolCall>? get toolCalls;
}
