/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:04:04.723355

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'message_metadata.zorphy.dart';
part 'message_metadata.g.dart';

/// MessageMetadata entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $MessageMetadata {

  int? get tokenCount;
  String? get model;
  double? get temperature;
  String? get provider;
  int? get latencyMs;
}

