/// Auto-generated by Zorphy
/// Generated at: 2026-02-18T22:57:05.950232

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'workspace_identity.zorphy.dart';
part 'workspace_identity.g.dart';

/// WorkspaceIdentity entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $WorkspaceIdentity {
  String get name;
  String? get persona;
  String? get systemPrompt;
  Map<String, dynamic>? get toolConfigs;
}
