import 'package:flutter/material.dart';
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/workspace/workspace.dart';
import '../../domain/entities/workspace_identity/workspace_identity.dart';
import '../../domain/usecases/workspace/create_workspace_usecase.dart';
import '../../domain/usecases/workspace/get_workspace_list_usecase.dart';
import '../../domain/usecases/workspace/get_workspace_usecase.dart';
import '../../domain/usecases/workspace/update_workspace_usecase.dart';
import '../../domain/usecases/workspace/delete_workspace_usecase.dart';
import '../state/workspace_state.dart';

/// Controller for managing workspace list and operations
class WorkspaceController extends ChangeNotifier {
  WorkspaceController(
    this._getWorkspaceListUseCase,
    this._getWorkspaceUseCase,
    this._createWorkspaceUseCase,
    this._updateWorkspaceUseCase,
    this._deleteWorkspaceUseCase,
  );

  final GetWorkspaceListUseCase _getWorkspaceListUseCase;
  final GetWorkspaceUseCase _getWorkspaceUseCase;
  final CreateWorkspaceUseCase _createWorkspaceUseCase;
  final UpdateWorkspaceUseCase _updateWorkspaceUseCase;
  final DeleteWorkspaceUseCase _deleteWorkspaceUseCase;

  WorkspaceState _state = WorkspaceState();
  WorkspaceState get state => _state;

  /// Load all workspaces from the API
  Future<void> loadWorkspaces({bool includeDeleted = false}) async {
    _state = _state.copyWith(isLoading: true, error: null);
    notifyListeners();

    try {
      final params = ListQueryParams<Workspace>(
        params: {'include_deleted': includeDeleted},
      );
      final workspaces = await _getWorkspaceListUseCase.execute(params, null);
      _state = _state.copyWith(workspaces: workspaces, isLoading: false);
      notifyListeners();
    } catch (e) {
      debugPrint('WorkspaceController loadWorkspaces error: $e');
      _state = _state.copyWith(
        isLoading: false,
        error: 'Failed to load workspaces: ${e.toString()}',
      );
      notifyListeners();
    }
  }

  /// Create a new workspace
  Future<Workspace?> createWorkspace({
    required String name,
    String? persona,
    String? systemPrompt,
    Map<String, dynamic>? toolConfigs,
    required String gatewayConnectionId,
  }) async {
    _state = _state.copyWith(isCreating: true, error: null);
    notifyListeners();

    try {
      final workspace = Workspace(
        id: '', // Will be generated by server
        identity: WorkspaceIdentity(
          name: name,
          persona: persona,
          systemPrompt: systemPrompt,
          toolConfigs: toolConfigs,
        ),
        gatewayConnectionId: gatewayConnectionId,
        createdAt: DateTime.now(),
      );

      final created = await _createWorkspaceUseCase.execute(workspace, null);
      
      // Add to local list
      final updatedList = [..._state.workspaces, created];
      _state = _state.copyWith(
        workspaces: updatedList,
        isCreating: false,
      );
      notifyListeners();
      
      return created;
    } catch (e) {
      debugPrint('WorkspaceController createWorkspace error: $e');
      _state = _state.copyWith(
        isCreating: false,
        error: 'Failed to create workspace: ${e.toString()}',
      );
      notifyListeners();
      return null;
    }
  }

  /// Update an existing workspace
  Future<Workspace?> updateWorkspace({
    required String workspaceId,
    String? name,
    String? persona,
    String? systemPrompt,
    Map<String, dynamic>? toolConfigs,
  }) async {
    _state = _state.copyWith(isUpdating: true, error: null);
    notifyListeners();

    try {
      final updateData = <String, dynamic>{};
      
      if (name != null || persona != null || systemPrompt != null || toolConfigs != null) {
        updateData['identity'] = <String, dynamic>{};
        if (name != null) updateData['identity']['name'] = name;
        if (persona != null) updateData['identity']['persona'] = persona;
        if (systemPrompt != null) updateData['identity']['systemPrompt'] = systemPrompt;
        if (toolConfigs != null) updateData['identity']['toolConfigs'] = toolConfigs;
      }

      final params = UpdateParams<String, Partial<Workspace>>(
        id: workspaceId,
        data: updateData,
      );

      final updated = await _updateWorkspaceUseCase.execute(params, null);
      
      // Update local list
      final index = _state.workspaces.indexWhere((w) => w.id == workspaceId);
      if (index != -1) {
        final updatedList = [..._state.workspaces];
        updatedList[index] = updated;
        _state = _state.copyWith(workspaces: updatedList, isUpdating: false);
      } else {
        _state = _state.copyWith(isUpdating: false);
      }
      notifyListeners();
      
      return updated;
    } catch (e) {
      debugPrint('WorkspaceController updateWorkspace error: $e');
      _state = _state.copyWith(
        isUpdating: false,
        error: 'Failed to update workspace: ${e.toString()}',
      );
      notifyListeners();
      return null;
    }
  }

  /// Delete a workspace (soft delete)
  Future<bool> deleteWorkspace(String workspaceId) async {
    _state = _state.copyWith(isDeleting: true, error: null);
    notifyListeners();

    try {
      final params = DeleteParams<String>(id: workspaceId);
      await _deleteWorkspaceUseCase.execute(params, null);
      
      // Update local list - mark as deleted or remove
      final updatedList = _state.workspaces.where((w) => w.id != workspaceId).toList();
      _state = _state.copyWith(
        workspaces: updatedList,
        isDeleting: false,
      );
      notifyListeners();
      
      return true;
    } catch (e) {
      debugPrint('WorkspaceController deleteWorkspace error: $e');
      _state = _state.copyWith(
        isDeleting: false,
        error: 'Failed to delete workspace: ${e.toString()}',
      );
      notifyListeners();
      return false;
    }
  }

  /// Select a workspace
  void selectWorkspace(Workspace workspace) {
    _state = _state.copyWith(selectedWorkspace: workspace);
    notifyListeners();
  }

  /// Clear error
  void clearError() {
    _state = _state.copyWith(error: null);
    notifyListeners();
  }

  /// Refresh the workspace list
  Future<void> refresh() async {
    await loadWorkspaces();
  }
}
