/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:04:04.251660

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/autonomy_level.dart';

part 'identity_config.zorphy.dart';
part 'identity_config.g.dart';

/// IdentityConfig entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $IdentityConfig {
  String get name;
  String? get personality;
  String? get systemPrompt;
  String get model;
  double get temperature;
  AutonomyLevel get autonomyLevel;
}
