/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:04:04.361584

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'tool_scope.zorphy.dart';
part 'tool_scope.g.dart';

/// ToolScope entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $ToolScope {

  List<String>? get allowedDirectories;
  List<String>? get allowedDomains;
  List<String>? get allowedCommands;
  bool get workspaceOnly;
}

