/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:04:04.602195

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'attachment.zorphy.dart';
part 'attachment.g.dart';

/// Attachment entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $Attachment {
  String get id;
  String get filename;
  String get mimeType;
  int get sizeBytes;
  String? get localPath;
  String? get url;
}
