/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:03:22.955464

import 'package:zorphy_annotation/zorphy_annotation.dart';

import '../enums/index.dart';

part 'gateway_connection.zorphy.dart';
part 'gateway_connection.g.dart';

/// GatewayConnection entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $GatewayConnection {
  String get id;
  String get name;
  String get url;
  String? get pairingCode;
  String? get bearerToken;
  DateTime? get tokenExpiresAt;
  ConnectionStatus get status;
  DateTime? get lastConnectedAt;
  String? get lastError;
  DateTime? get lastErrorAt;
  DateTime get createdAt;
  DateTime get updatedAt;
}
