/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:03:22.651244

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../identity_config/identity_config.dart';
import '../tool_configuration/tool_configuration.dart';

part 'workspace.zorphy.dart';
part 'workspace.g.dart';

/// Workspace entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $Workspace {

  String get id;
  String get name;
  String? get description;
  String? get gatewayConnectionId;
  $IdentityConfig get identityConfig;
  List<$ToolConfiguration> get toolConfigurations;
  String? get activeConversationId;
  DateTime get createdAt;
  DateTime get updatedAt;
  bool get isDeleted;
}

