/// Auto-generated by Zorphy
/// Generated at: 2026-02-18T23:01:01.966031

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../workspace_identity/workspace_identity.dart';

part 'workspace.zorphy.dart';
part 'workspace.g.dart';

/// Workspace entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $Workspace {
  $WorkspaceIdentity get identity;
  String get gatewayConnectionId;
  DateTime get createdAt;
  DateTime? get updatedAt;
  DateTime? get deletedAt;
  String get id;
}
