import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

/// Hive database initialization and management
///
/// Handles:
/// - Box initialization for different data types
/// - Encrypted box for sensitive credentials
/// - Platform-specific secure storage for encryption keys
class HiveDatasource {
  static const String _workspaceBoxName = 'workspaces';
  static const String _conversationBoxName = 'conversations';
  static const String _messageBoxName = 'messages';
  static const String _gatewayBoxName = 'gateway_connections';
  static const String _toolConfigBoxName = 'tool_configurations';
  static const String _encryptedBoxName = 'secure_credentials';

  final FlutterSecureStorage _secureStorage = const FlutterSecureStorage();

  /// Initialize Hive database with all required boxes
  Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters for all entities
    // Note: Adapters will be auto-generated by Zuraffa/build_runner
    // Hive.registerAdapter(WorkspaceAdapter());
    // Hive.registerAdapter(ConversationAdapter());
    // Hive.registerAdapter(MessageAdapter());
    // Hive.registerAdapter(GatewayConnectionAdapter());
    // Hive.registerAdapter(ToolConfigurationAdapter());

    // Open standard boxes
    await Hive.openBox(_workspaceBoxName);
    await Hive.openBox(_conversationBoxName);
    await Hive.openBox(_messageBoxName);
    await Hive.openBox(_gatewayBoxName);
    await Hive.openBox(_toolConfigBoxName);

    // Open encrypted box for sensitive credentials
    await _openEncryptedBox();
  }

  /// Open encrypted box for storing bearer tokens and sensitive data
  Future<void> _openEncryptedBox() async {
    // Generate or retrieve encryption key from platform secure storage
    var encryptionKeyBytes = await _secureStorage.read(key: 'encryption_key');

    if (encryptionKeyBytes == null) {
      // Generate new key if not exists
      final key = Hive.generateSecureKey();
      encryptionKeyBytes = String.fromCharCodes(key);
      await _secureStorage.write(
        key: 'encryption_key',
        value: encryptionKeyBytes,
      );
    }

    // Open encrypted box
    await Hive.openBox(
      _encryptedBoxName,
      encryptionCipher: HiveAesCipher(encryptionKeyBytes.codeUnits),
    );
  }

  /// Get standard box by name
  Box<T> getBox<T>(String boxName) {
    return Hive.box<T>(boxName);
  }

  /// Get encrypted box for credentials
  Box<String> getEncryptedBox() {
    return Hive.box<String>(_encryptedBoxName);
  }

  /// Store bearer token securely
  Future<void> storeBearerToken(String connectionId, String token) async {
    final encryptedBox = getEncryptedBox();
    await encryptedBox.put('bearer_token_$connectionId', token);
  }

  /// Retrieve bearer token securely
  Future<String?> getBearerToken(String connectionId) async {
    final encryptedBox = getEncryptedBox();
    return encryptedBox.get('bearer_token_$connectionId');
  }

  /// Clear bearer token
  Future<void> clearBearerToken(String connectionId) async {
    final encryptedBox = getEncryptedBox();
    await encryptedBox.delete('bearer_token_$connectionId');
  }

  /// Close all boxes
  Future<void> close() async {
    await Hive.close();
  }
}
