/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T10:47:05.313956

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../message_metadata/message_metadata.dart';

part 'message.zorphy.dart';
part 'message.g.dart';

/// Message entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $Message {

  String get id;
  String get conversationId;
  MessageSender get sender;
  String get content;
  MessageStatus get status;
  DateTime get timestamp;
  int? get retryCount;
  String? get errorMessage;
  $MessageMetadata? get metadata;
}

