/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:03:22.847671

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../attachment/attachment.dart';
import '../enums/index.dart';
import '../message_metadata/message_metadata.dart';

import '../tool_call/tool_call.dart';

part 'message.zorphy.dart';
part 'message.g.dart';

/// Message entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $Message {
  String get id;
  String get conversationId;
  MessageSender get sender;
  String get content;
  DateTime get timestamp;
  MessageStatus? get status;
  List<$ToolCall>? get toolCalls;
  List<$Attachment>? get attachments;
  $MessageMetadata? get metadata;
  String? get replyToMessageId;
  bool get isEdited;
  DateTime? get editedAt;
}
