/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T01:03:22.746541

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../message/message.dart';

part 'conversation.zorphy.dart';
part 'conversation.g.dart';

/// Conversation entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $Conversation {

  String get id;
  String get workspaceId;
  String get title;
  List<$Message> get messages;
  DateTime get createdAt;
  DateTime get updatedAt;
  DateTime? get lastMessageAt;
  int get messageCount;
  bool get isArchived;
  Map<String, dynamic>? get metadata;
}

