/// Auto-generated by Zorphy
/// Generated at: 2026-02-17T10:46:43.758283

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'conversation.zorphy.dart';
part 'conversation.g.dart';

/// Conversation entity
@Zorphy(generateJson: true, generateCompareTo: true, generateFilter: true)
abstract class $Conversation {
  String get id;
  String? get workspaceId;
  String get title;
  List<String> get messageIds;
  DateTime get createdAt;
  DateTime get updatedAt;
  DateTime? get lastMessageAt;
  int get messageCount;
  bool get isArchived;
}
